//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_LX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorLog
    {
        public int LogId { get; set; }
        public System.DateTime DateAndTime { get; set; }
        public string Message { get; set; }
        public string Origin { get; set; }
        public Nullable<int> UserId { get; set; }
    }
}
