//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_LX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int id_usuario { get; set; }
        public string cedula { get; set; }
        public string fecha_nacimiento { get; set; }
        public string nombre { get; set; }
        public string email { get; set; }
        public string contrasena { get; set; }
        public int id_rol { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<long> StatusId { get; set; }
        public Nullable<System.DateTime> lastactivity { get; set; }
    
        public virtual Rol Rol { get; set; }
        public virtual Status Status { get; set; }
    }
}
